export default [
    {
        id: 1,
        image: "./src/images/table-css.png",
        tags: "Technology",
        title: "Effect Underline Hover in Nav Itens in Navbar",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove",
    },
    {
        id: 2,
        image: "//images.unsplash.com/photo-1594904351111-a072f80b1a71?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=400&ixid=MnwxfDB8MXxyYW5kb218MHx8cHJvZ3JhbW1pbmd8fHx8fHwxNjQxMzg3NzUy&ixlib=rb-1.2.1&q=80&utm_campaign=api-credit&utm_medium=referral&utm_source=unsplash_source&w=400",
        tags: "Technology",
        title: "Check Out The Most Awesome VR Headset in 2020",
        description: "I neglect my talents Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated",
    },
    {
        id: 3,
        image: "./src/images/navbar-css.png",
        tags: "Trending",
        title: "Flexbox Navbar CSS Bar (Clone)",
        description: "I neglect my talents Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated",
    },
    {
        id: 4,
        image: "//a6e8z9v6.stackpathcdn.com/akea/homepage3/wp-content/uploads/2018/11/christopher-burns-271403-unsplash-400x400.jpg",
        tags: "Trending",
        title: "XE Entertainment Brings You New Experience of Fun",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove",
    },
    {
        id: 5,
        image: "//a6e8z9v6.stackpathcdn.com/akea/homepage3/wp-content/uploads/2018/11/pexels-photo-736166-400x400.jpeg",
        tags: "Headline",
        title: "Top Amazing Places to Go in Summer",
        description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove",
    },
    {
        id: 6,
        image: "//a6e8z9v6.stackpathcdn.com/akea/homepage3/wp-content/uploads/2018/11/pexels-photo-871053-400x400.jpeg",
        tags: "Travel",
        title: "9 Most Awesome Blue Lake With Snow Mountain",
        description: "I neglect my talents Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated",
    },
    // {
    //     id: 7,
    //     image: "",
    //     tags: "",
    //     title: "",
    //     description: "",
    // },
]