export default [
    {
        id: 1,
        image: "ui-design-502",
        tags: " menu, card ui",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/KKXryGv",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-card-components-menu-day-502",
        title: "Card Components",
        description: "Three components (menu, cards, sidebar icons) made with flexbox, grid-areas and BEM (Block Element Modifier) methodology",
    },
    {
        id: 2,
        image: "ui-design-1439",
        tags: "search, tags ui",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/QWqRXpx",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-search-section-day-1439",
        title: "Search Section",
        description: "Clean search section card made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 3,
        image: "ui-design-1451",
        tags: "profile, card, user ui",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/rNYNWNV",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-user-profile-card-day-1451",
        title: "User Profile",
        description: "Simple user profile card made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 4,
        image: "ui-design-1520",
        tags: "form, radio, checkbox ui",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/oNGmLjo",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-settings-day-1520",
        title: "Settings",
        description: "Beautiful settings (radio, checkbox) made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 5,
        image: "ui-design-1524",
        tags: "job list, card",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/WNZLwqe",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-job-cards-list-card-day-1524",
        title: "Job Cards",
        description: "Wonderful list of job cards made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 6,
        image: "ui-design-1528",
        tags: "sign up, authentication",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/MWEMBLR",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-sign-up-authentication-day-1528",
        title: "Sign Up",
        description: "Clean sign up made with grid CSS, inline-block and BEM (Block Element Modifier) methodology",
    },
    // {
    //     id: 7,
    //     image: "",
    //     tags: "",
    //     title: "",
    //     description: "",
    // },
]