export default [
    {
        id: 1,
        image: "ui-design-1429",
        tags: "footer, dark theme",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/jOGoWZW",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-footer-ui-design-dark-theme-day-1429",
        title: "Footer UI Design",
        description: "Simple footer ui design made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 2,
        image: "ui-design-1459",
        tags: "footer, article",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/OJxKWBj",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-article-footer-day-1459",
        title: "Article Footer",
        description: "Simple sign up card made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 3,
        image: "ui-design-1475",
        tags: "tags, card",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/qBPwrPK",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-ui-components-tags-card-day-1475",
        title: "UI Components",
        description: "Two cards components with tags, buttons made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 4,
        image: "ui-design-1487",
        tags: "search, tags, dark mode",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/JjOPJRe",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-search-tags-dark-mode-day-1487",
        title: "Search (dark mode)",
        description: "Future search (dark mode) card made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 5,
        image: "ui-design-1494",
        tags: "menu, card",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/vYePrgG",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-menu-card-day-1494",
        title: "Card",
        description: "Simple card (with attributes) made with flexbox, grid and BEM (Block Element Modifier) methodology",
    },
    {
        id: 6,
        image: "ui-design-1519",
        tags: "log in, authentication",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/PoJVOKL",
        fontUrl: "https://www.uidesigndaily.com/posts/figma-log-in-authentication-day-1519",
        title: "Log In",
        description: "Beautiful Log In component (with options) made with grid and BEM (Block Element Modifier) methodology",
    },
    // {
    //     id: 7,
    //     image: "",
    //     tags: "",
    //     title: "",
    //     description: "",
    // },
]