export default [
    {
        id: 1,
        image: "zoomIn",
        tags: "Animação CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/WNXreMz",
        title: "Zoom In",
        description: "Zoom In é uma animação que começa pequena ao fundo e aumenta (increase) lentamente para a parte central da tela",
    },
    {
        id: 2,
        image: "zoomInDown",
        tags: "Animação CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/dyZGbwX",
        title: "Zoom In Down",
        description: "Zoom In Down é uma animação que começa pequena na parte superior da tela e aumenta (increase) para baixo lentamente",
    },
    {
        id: 3,
        image: "zoomInRight",
        tags: "Effect Zoom",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/oNobvOL",
        title: "Zoom In Right",
        description: "Zoom In Left é uma animação que começa pequena na parte esquerda da tela e aumenta (increase) para direita lentamente",
    },
    {
        id: 4,
        image: "zoomInUp",
        tags: "Effect Zoom",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/abVdbbv",
        title: "Zoom In Up",
        description: "Zoom In Up é uma animação que começa pequena na parte inferior da tela e aumenta (increase) para cima lentamente",
    },
    {
        id: 5,
        image: "zoomInLeft",
        tags: "Effect Zoom",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/oNobvVL",
        title: "Zoom In Left",
        description: "Zoom In Left é uma animação que começa pequena na parte direita da tela e aumenta (increase) para esquerda lentamente",
    },
    {
        id: 6,
        image: "FadeInRight",
        tags: "Fade CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/zYPvVeZ",
        title: "Fade In Right",
        description: "Fade In Right é uma animação que desliza na parte esquerda da tela e desvanece (fade) para direita lentamente",
    },
    {
        id: 7,
        image: "FadeInUp",
        tags: "Fade CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/JjOYqpj",
        title: "Fade In Up",
        description: "Fade In Up é uma animação que desliza na parte de baixo da tela e desvanece (fade) para cima lentamente",
    },
    {
        id: 8,
        image: "FadeInLeft",
        tags: "Fade CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/wvPKLYZ",
        title: "Fade In Left",
        description: "Fade In Left é uma animação que desliza na parte direita da tela e desvanece (fade) para esquerda lentamente",
    },
    {
        id: 9,
        image: "FadeInDown",
        tags: "Fade CSS",
        codeUrl: "https://codepen.io/contatosraphaelmoreira/pen/OJOyeva",
        title: "Fade In Down",
        description: "Fade In Down é uma animação que desliza na parte de cima da tela e desvanece (fade) para baixo lentamente",
    },
    // {
    //     id: 4,
    //     image: "",
    //     tags: "",
    //     title: "",
    //     description: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove",
    // },
    // {

    // }
]